name: update-gh-activity

on:
  push:
    branches: [main]
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-activity:
    name: Update recent activity section
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ Update recent activity"
          MAX_LINES: 5
          FILTER_EVENTS: "PushEvent,WatchEvent,IssuesEvent,IssueCommentEvent,PullRequestEvent,ReleaseEvent,ForkEvent,CreateEvent"
